/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.jackcholt.reveal;

public final class R {
    public static final class array {
        public static final int fileEndingAudio=0x7f060001;
        public static final int fileEndingImage=0x7f060000;
        public static final int fileEndingPackage=0x7f060002;
        public static final int fileEndingText=0x7f060004;
        public static final int fileEndingWebText=0x7f060003;
        public static final int fileEndingYbk=0x7f060005;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int font_size=0x7f080000;
        public static final int large_font_size=0x7f080001;
    }
    public static final class drawable {
        public static final int folder=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int mainimage=0x7f020002;
        public static final int reveal=0x7f020003;
        public static final int splash=0x7f020004;
        public static final int text=0x7f020005;
        public static final int uponelevel=0x7f020006;
        public static final int webtext=0x7f020007;
        public static final int ywd=0x7f020008;
    }
    public static final class id {
        public static final int bookButton=0x7f090009;
        public static final int bookText=0x7f090002;
        public static final int breadCrumb=0x7f090007;
        public static final int button1=0x7f090005;
        public static final int chapterButton=0x7f09000a;
        public static final int close_about_btn=0x7f090001;
        public static final int help_container=0x7f090000;
        public static final int historylist=0x7f090004;
        public static final int mainMenu=0x7f090008;
        public static final int selection=0x7f090006;
        public static final int widget0=0x7f090003;
        public static final int ybkView=0x7f09000b;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int book_list_row=0x7f030001;
        public static final int browser_list_item=0x7f030002;
        public static final int browser_main=0x7f030003;
        public static final int history=0x7f030004;
        public static final int main=0x7f030005;
        public static final int view_ybk=0x7f030006;
    }
    public static final class raw {
        public static final int xmlbooks=0x7f050000;
    }
    public static final class string {
        public static final int alert_dialog_ok=0x7f07000e;
        public static final int app_name=0x7f070000;
        public static final int author=0x7f070023;
        public static final int checking_ebooks=0x7f070021;
        public static final int close=0x7f070026;
        public static final int contact=0x7f070024;
        public static final int default_ebook_dir=0x7f070012;
        public static final int default_fontsize=0x7f070015;
        public static final int default_temp_dir=0x7f070013;
        public static final int dialog_title_list_preference=0x7f07001b;
        public static final int ebook_update_complete=0x7f070022;
        public static final int label_splash_screen=0x7f070006;
        public static final int library_not_created=0x7f07001e;
        public static final int menu_about=0x7f070011;
        public static final int menu_bookmark=0x7f070002;
        public static final int menu_browser=0x7f070007;
        public static final int menu_history=0x7f070003;
        public static final int menu_next=0x7f07001d;
        public static final int menu_previous=0x7f07001c;
        public static final int menu_refresh_library=0x7f070005;
        public static final int menu_settings=0x7f070004;
        public static final int menu_update=0x7f070010;
        public static final int midnightmode_off=0x7f070014;
        public static final int midnightmode_on=0x7f070016;
        public static final int no_books=0x7f070001;
        public static final int reference_not_found=0x7f07000d;
        public static final int reveal_ybk_view=0x7f07000c;
        public static final int settings_name=0x7f070008;
        public static final int summary_default_ebook_dir=0x7f070017;
        public static final int summary_default_temp_dir=0x7f070018;
        public static final int summary_list_preference=0x7f07001a;
        public static final int summary_off_show_splash_screen=0x7f07000a;
        public static final int summary_on_show_splash_screen=0x7f070009;
        public static final int title_browser_name=0x7f07000f;
        public static final int title_download_url=0x7f070027;
        public static final int title_list_preference=0x7f070019;
        public static final int up_one_level=0x7f07000b;
        public static final int update_browser=0x7f07001f;
        public static final int update_url=0x7f070020;
        public static final int website=0x7f070025;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
